version: '3'

services:
  api:
    build: ./api
    ports:
      - "8080:5000"
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: data_mart_airbnb
    ports:
      - "3306:3306"
    volumes:
      - "./mydb/data_mart_airbnb.sql:/docker-entrypoint-initdb.d/4.sql"
  
  
