version : '3'
services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - "./scripts/createTable.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./scripts/addPK.sql:/docker-entrypoint-initdb.d/2.sql"
      - "./scripts/addFK.sql:/docker-entrypoint-initdb.d/3.sql"
      - "./scripts/modifydb.sql:/docker-entrypoint-initdb.d/4.sql"



