apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: api-deploy
  name: api-deploy
  namespace: app-space
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: api-deploy
  type: NodePort
status:
  loadBalancer: {}
