apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "datamarthelm.fullname" . }}
  labels:
    {{- include "datamarthelm.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "datamarthelm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "datamarthelm.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: certvolume
          secret:
            secretName: broker-certs
      serviceAccountName: {{ include "datamarthelm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: KAFKA_BROKER_HOST
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_BROKER_HOST
                  name: env
            - name: KAFKA_BROKER_PORT
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_BROKER_PORT
                  name:  env
            - name: TOPIC
              valueFrom:
                configMapKeyRef:
                  key: TOPIC
                  name:  env
            - name: CERTLOCATION
              valueFrom:
                configMapKeyRef:
                  key: CERTLOCATION
                  name:  env
            - name: CLIENTPUB
              valueFrom:
                configMapKeyRef:
                  key: CLIENTPUB
                  name:  env
            - name: CLIENTKEY
              valueFrom:
                configMapKeyRef:
                  key: CLIENTKEY
                  name:  env
            - name: CA
              valueFrom:
                configMapKeyRef:
                  key: CA
                  name:  env
          volumeMounts:
            - name:  certvolume
              mountPath: {{.Values.env.certLocation}}
              readOnly: true
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
