apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - image: giprocida/flask_api:local
          imagePullPolicy: Never
          name: api
          envFrom: 
           - configMapRef:
               name: my-config
          volumeMounts: 
           - name: my-secret
             mountPath: /app/client-cert
             readOnly: false
      volumes:
        - name: my-config
          configMap: 
            name: my-config
        - name: my-secret
          secret: 
            secretName: my-secret                      
      restartPolicy: Always
status: {}
